language: python
python:
  - "3.7.4"
before_install:
  - pip install --user codecov
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt
script:
  - python manage.py test
after_success:
  - codecov --file coverage/lcov.info --disable search
